# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 19:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0003_auto_20160628_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_msg', models.DateTimeField(auto_now_add=True)),
                ('text_msg', models.TextField()),
                ('user_msg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.UserProfile')),
            ],
        ),
    ]
